import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

async function render(path = "/") {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request(`http://localhost${path}`, { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the launch landing page", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /See your Codex and ChatGPT allowance before you hit the limit/);
  assert.match(html, /Use your plan deliberately/);
  assert.match(html, /Download for Mac/);
  assert.match(html, /Simulate heavy session/);
  assert.match(html, /Switch themes\. Burn the allowance/);
  assert.match(html, /Download Gaugelet 1\.0/);
  assert.match(html, /Five-minute refresh/);
  assert.match(html, /Seven in-app themes\. One clear gauge/);
  assert.match(html, /menu bar keeps a clean adaptive half-gauge/);
  assert.match(html, /src="\/images\/gaugelet-menubar\.svg"/);
  assert.match(html, /Made for Apple silicon/);
  assert.match(html, /Local-first privacy/);
  assert.match(html, /Independent maker in Panama/);
  assert.match(html, /Buy me a coffee/);
  assert.match(
    html,
    /href="https:\/\/www\.paypal\.com\/donate\/\?hosted_button_id=Z4QV6SJVXSCH4"/,
  );
  assert.doesNotMatch(html, /Coffee link coming before launch/);
  assert.match(html, /OpenAI’s enforced limits remain authoritative/);
  assert.match(html, /Built by LammWorks/);
  assert.match(html, /<link rel="canonical" href="https:\/\/gaugelet\.wonkytonks\.chatgpt\.site"/);
  assert.match(html, /<link rel="icon" href="\/favicon\.svg" type="image\/svg\+xml"/);
  assert.match(html, /<meta property="og:image" content="https:\/\/gaugelet\.wonkytonks\.chatgpt\.site\/images\/gaugelet-social\.jpg"/);
  assert.match(html, /<meta name="twitter:card" content="summary_large_image"/);
  assert.doesNotMatch(html, /real[- ]time|exact credits|always exactly three/i);
  assert.doesNotMatch(html, /Your site is taking shape|Building your site/);
});

for (const route of [
  ["/install", "Install Gaugelet 1.0"],
  ["/privacy", "Gaugelet privacy notice"],
  ["/support", "Gaugelet support"],
  ["/security", "Gaugelet security policy"],
  ["/changelog", "Changelog"],
]) {
  test(`server-renders canonical content at ${route[0]}`, async () => {
    const response = await render(route[0]);
    assert.equal(response.status, 200);
    const html = await response.text();
    assert.match(html, new RegExp(route[1], "i"));
    assert.match(html, /Built by LammWorks/);
    assert.match(
      html,
      new RegExp(`<link rel="canonical" href="https://gaugelet\\.wonkytonks\\.chatgpt\\.site${route[0]}"`),
    );
  });
}

test("keeps canonical Markdown synchronized and release assets local", async () => {
  const [generated, install, privacy] = await Promise.all([
    readFile(new URL("../app/content.generated.ts", import.meta.url), "utf8"),
    readFile(new URL("../../INSTALL.md", import.meta.url), "utf8"),
    readFile(new URL("../../PRIVACY.md", import.meta.url), "utf8"),
  ]);

  assert.match(generated, /Generated by scripts\/sync-content\.mjs/);
  assert.ok(generated.includes(JSON.stringify(install.replace(/\r\n/g, "\n"))));
  assert.ok(generated.includes(JSON.stringify(privacy.replace(/\r\n/g, "\n"))));
  await Promise.all([
    "gaugelet-dashboard.png",
    "gaugelet-icon.png",
    "gaugelet-menubar.svg",
    "launch-orbit-background.png",
    "gaugelet-social.jpg",
    "product-hunt-thumbnail.jpg",
    "product-hunt-gallery-1.jpg",
    "product-hunt-gallery-2.jpg",
  ].map((filename) => access(new URL(`../public/images/${filename}`, import.meta.url))));
});

test("all rendered internal links resolve", async () => {
  const routes = ["/", "/install", "/privacy", "/support", "/security", "/changelog"];
  const internal = new Set(routes);

  for (const route of routes) {
    const response = await render(route);
    const html = await response.text();
    for (const match of html.matchAll(/<a\b[^>]*\shref="(\/[^"#?]*)(?:[#?][^"]*)?"/g)) {
      internal.add(match[1] || "/");
    }
  }

  for (const route of [...internal].sort()) {
    const response = await render(route);
    assert.equal(response.status, 200, `broken internal link: ${route}`);
  }
});
