import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const websiteRoot = resolve(scriptDirectory, "..");
const repositoryRoot = resolve(websiteRoot, "..");
const outputPath = resolve(websiteRoot, "app/content.generated.ts");
const sources = ["INSTALL.md", "PRIVACY.md", "SUPPORT.md", "SECURITY.md", "CHANGELOG.md"];

const documents = Object.fromEntries(
  sources.map((filename) => [
    filename,
    readFileSync(resolve(repositoryRoot, filename), "utf8").replace(/\r\n/g, "\n"),
  ]),
);

const output = [
  "// Generated by scripts/sync-content.mjs from canonical repository Markdown.",
  "// Do not edit this file directly.",
  `export const documents = ${JSON.stringify(documents, null, 2)} as const;`,
  "",
].join("\n");

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(outputPath, "utf8");
  } catch {
    // A missing generated file is reported by the comparison below.
  }
  if (current !== output) {
    console.error("Canonical site content is stale. Run: npm run sync:content");
    process.exit(1);
  }
} else {
  writeFileSync(outputPath, output);
  console.log(`Synced ${sources.length} canonical documents.`);
}
